name: lyricscribe
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  cloud_functions: ^4.5.2
  file_picker: ^6.0.0
  firebase_auth: ^4.12.0
  firebase_core: ^2.20.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_lyric: ^2.0.4+6
  freezed_annotation: ^2.4.1
  hive: ^2.2.3
  hooks_riverpod: ^2.4.4
  json_annotation: ^4.8.1
  just_audio: ^0.9.35

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.1
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/music1.mp3
    - assets/bg.jpeg
